### ISSUE TITLE
stopping the casting prevents one from casting again

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#12]
If one shuts down the casting the app will hide the Chromecast icon, so one couldn't cast again immediately after (e.g. to another device). Leaving the grid display and restarting it does work around this.

**Comment by quentin-st** [comment]
Hi!

I worked a little bit on the receiver (complete JS refactoring). I tried to reproduce your issue but I couldn't.
I'm assuming this is fixed, so I'll close this issue: don't hesitate to reopen it it you're still experiencing this behavior.

Thanks for the bug report!
