### ISSUE TITLE
panning on zoomed graphs is hard

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#15]
If one tries to zoom a graph and pans around this graph, the graph should never start switching to another one.

Quite often I want to view the data at the edges of the graph (e.g. the latest data) and when I am nearly there it already starts switching to the next graph. I think there should be much harder "resistance" when switching between graphs, especially in a zoomed view. Alternatively switching between graphs should only be possible by swiping in from an edge.

**Comment by quentin-st** [comment]
It has been difficult to find a zooming library which doesn't conflict with the ViewPager.
Even if this library fits our needs, it isn't perfect.

I just realized that I used another library to create the ViewPager (org.taptwo.android.widget.ViewFlow). This library hasn't been updated for 3 years so it is urgent to get rid of it! I just created a new branch where I'm trying to clean this mess. The vanilla ViewPager works fine (I'm using it on some other applications), and is much more fluid than the library we're using right now.

This change may fix some of the conflicts between the PhotoView (zoomable ImageView) and the ViewPager.

Once I'll have finished the cleaning, I'm planning to release a beta2 version so you'll be able to test!

**Comment by quentin-st** [comment]
I just merged `graphview_mess_cleaning` with master. As expected, everything works much better now!
There's no more conflict between PhotoView and the ViewPager, and animations are way more fluid.
I'm currently publishing a beta2 version so everything can try this.

**Comment by klaernie** [comment]
:+1:
