### ISSUE TITLE
grids shouldn't loose data when removing/re-adding servers

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#18]
The grids should store the plugins by referencing the master, server name and plugin name instead of an internal ID that gets lost as soon as the server gets removed.

**Comment by quentin-st** [comment]
That's a question I asked myself... Unfortunately, lose relations like this are too weak: two masters can have the same name, same with servers, same with plugins...
Also, it would lower performances when getting/saving GridItems, and make the database size bigger...

But we have to find a way to keep those grids indeed. Currently, GridItems are re-attached to new objects when rescanning a master. We could use a similar way to keep them, don't you think?

**Comment by klaernie** [comment]
Despite these pieces of information are not guaranteed to be unique they make great hints. I think this hint should be stored and when a grid gets loaded, that is missing graphs, it should try to recover them, and if it fails ask the use if they should get removed or if it should get replaced with another one.

In contrast to rescanning we don't exactly have the old plugin list and the new one for a given master/server combination available, so I assume it would be hard to reuse the existing algorithm.

**Comment by quentin-st** [comment]
Ok, now I see!
We can still keep the way foreign key are managed. But when a Master (therefore its Servers) are deleted, we could put the GridItem.serverId to -1, but store the master/server/plugin information in 3 separate columns.
Then, if the user displays a grid with "broken" GridItems, we allow him to delete those.
When a server is added, we try to reattach any existing broken GridItem.

That's indeed better! :)

**Comment by klaernie** [comment]
Sounds like a solid plan. :+1:
