### ISSUE TITLE
dynazoom should get auto-detected when activating

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#19]
The dynazoom URL should get auto-detected as soon as its enabled, and should get stored permanently.

Currently this setting is list quite often (as if it's bound to the currently active activity/instance and not persisted in any way)

**Comment by quentin-st** [comment]
This URL is detected as soon as the server is added, and persisted in [MuninServer.hdGraphUrl](https://github.com/chteuchteu/Munin-for-Android/blob/master/muninforAndroid/src/main/java/com/chteuchteu/munin/obj/MuninServer.java#L23).

Have you had any problem with this URL not being detected/being detected everytime?

**Comment by quentin-st** [comment]
There was actually an issue where dynazoom availability wasn't detected correctly when adding a server. This issue was closed by 2033d9a
