### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#2]
The app is available in four languages (English, French, German and Russian). Since I neither speak German nor Russian, some strings are missing translations.

From now, we were using POEditor, an online collaborative tool, but
1. Its free version only allows 1000 strings (Munin for Android contains 920)
2. It wasn't linked with the repository

We're now using Weblate.org, an online collaborative tool synced with the resource files on the GitHub repository. (You can display and review translations on the project page.)[https://hosted.weblate.org/projects/munin-for-android/strings/]

If you fluently speak German or Russian, a little help would be appreciated! :)

For sure, if you think that one of the current translations (in any language) could be enhanced, don't hesitate to contribute!

If you speak any other language and want to add it to the app, please do!

Thank you!

**Comment by klaernie** [comment]
Did you consided [Weblate](http://weblate.org/en/hosting/)? I would love to help out for german.

**Comment by quentin-st** [comment]
Thanks for the suggestion! Weblate seems great! I'm currently asking for an account on the tool.
Edit: Munin for Android is now on Weblate! https://hosted.weblate.org/projects/munin-for-android/strings/

**Comment by MrMitch** [comment]
You could add a link to weblate on munin-for-android.com, and maybe show a quick message in the app if the current phone language isn't one of the available languages to encourage people to help with the translations and bring new languages to the app

**Comment by quentin-st** [comment]
Thanks for the idea! munin-for-android.com updated, I also added it on the readme since it is the first thing new contributors see when coming aboard. I'll integrate the AlertDialog today!

For information purpose:
![screenshot from 2015-01-17 10 31 18](https://cloud.githubusercontent.com/assets/1551971/5788409/303c59e0-9e34-11e4-9e64-249205098a6a.png)
We're currently covering 70% of the users languages, which is nice!

**Comment by klaernie** [comment]
@chteuchteu Could you check if the repository URL linking to the source files in Weblate is correct? Usually Weblate provides a Repository Browse URL (http://docs.weblate.org/en/latest/admin/projects.html#component-configuration) that should point directly to the file underlying the translation.

**Comment by quentin-st** [comment]
@klaernie Since the project hosting is supplied by weblate.org, I can't edit the project configuration. I'll contact weblate administrators in order to fix this!

**Comment by xp-vit** [comment]
Just completed Russian translation. Hope this helps :)
https://github.com/chteuchteu/Munin-for-Android/pull/30

**Comment by quentin-st** [comment]
Awesome, thank you very much!

**Comment by quentin-st** [comment]
Closing this, since it is documented in main README and should not stay open
