### ISSUE TITLE
grids should get displayed in the drawer

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#21]
The drawer should directly show the available grids, like the graphs section does.

**Comment by quentin-st** [comment]
When there are two grids and more, the Toolbar shows a dropdown allowing user to switch from one grid to another. Given that, I don't think is it necessary to show the grids list in the drawer

**Comment by klaernie** [comment]
I know. I noticed that and thought about the consistency between the grids and the graphs section. I think it is generally a good idea to keep the places to choose from small, and not make the user hunt around for the places to navigate.

**Comment by quentin-st** [comment]
Consistency should indeed be kept between grids and graphs.
I actually have an idea for graphs: we could remove the plugins list from the drawer, and display the current plugin within a dropdown menu in the toolbar (alongside with the icons). The drawer would then regain usability (user wouldn't have to scroll to bottom of list to go the grids screen for example).

We could also add a dropdown menu on the server name currently displayed under the toolbar, as a "change server" feature.
