### ISSUE TITLE
Multiple levels on munin.conf cause duplicated servers

### ISSUE THREAD

**Issue by aalmenar** [chteuchteu/Munin-for-Android#23]
If you have multi-level configuration in your munin server like:

[Server;Sub-section1;node-name]
  address x.x.x.x

[Server;Sub-section2;node-name2]
  address y.y.y.y

When servers are scanned on munin app, they get duplicated on the list.

I have been looking at the source code, but been unable to find the reason of it.

**Comment by quentin-st** [comment]
Hi, thank you for the bug report!

Could you dump the main page HTML please (the list part)? I think that the app doesn't understand the nodes hierarchy very well.

Also, which version of munin are you running?

**Comment by aalmenar** [comment]
Munin Version is 2.0.25

Sorry, i no longer have the page, because it was so painful to use it (On the app), that I had to change it to one level.

I could try to make some sample records. Which parte of the page exactly do you need ?

**Comment by quentin-st** [comment]
Thank you for your help!

Could you provide everything inside `ul.groupview` HTML tag please? (the highlighted one in the following screenshot)
If it contains sensible information (like URLs), don't hesitate to replace any IP or domain name to dull strings.

![screenshot from 2015-07-12 16 57 20](https://cloud.githubusercontent.com/assets/1551971/8638300/69dfa540-28b7-11e5-9a4d-53de10d0879e.png)

**Comment by aalmenar** [comment]
The only one configured like this is

Email/Gateways

The html inside groupview is available here: https://gist.github.com/aalmenar/7271634f8742f2a61d77

**Comment by quentin-st** [comment]
So Email/Gateways is duplicated, right?
Thank you for your help, I'll check the app and get in touch soon

**Comment by aalmenar** [comment]
Yes those get duplicated in all lists showing server names.

**Comment by aalmenar** [comment]
Also, if you need any help, i've opted-in on the beta test of the app.

**Comment by quentin-st** [comment]
I found the faulty code part!

When scanning the nodes list, the app blindly get every `span.domain` DOM elements. In your case, there is one `span.domain` inside another. In this case, the child `span.host` is actually contained in both, and gets added twice:

```
span.domain (Email)
    span.domain (Gateways)
        span.host (mg1.domain.tld)
        span.host (mg2.domain.tld)
        ...
```

Bugfix incoming

**Comment by quentin-st** [comment]
I just published `v3.6.3-beta1` update, please let me know if it fixes the issue!

**Comment by aalmenar** [comment]
Works perfectly no more repeated hosts

Thanks!

**Comment by quentin-st** [comment]
Glad to hear it! Thank you for your help!
