### ISSUE TITLE
Push notifications from server to Android device

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#26]
For now, Munin for Android is polling each server from time to time to see if everything is OK.
@edovino Was the first to let me know that this is not the best way to do. Indeed, if a CPU spike happens between two polls, it won't be reported to user.

I'd like to refactor the whole notifications process. This will be done in two steps:
## 1- Individual notifications

One alert will trigger one notification, instead of one notification for all alerts. This will allow dismissing an alert for 1 hour, 1 day or forever. This will also make the whole feature easier to understand for new users.
## 2- Push to device

Instead of Munin for Android polling each munin installation, one small program will be called when an alert is triggered on the server. This program will take all the necessary information and send those using Google Cloud Messaging API (or whatever) to the device.
Notifications will be shown on user device if it hasn't been ignored.

This will allow way lower data consumption, and real time notifications.
The program could be written in Python (cool, easy to learn, read, maintain and debug), and of course open source too.
The whole process will be documented in order to be easy to install.
### Munin alert -> script

Interfacing munin with a small script is really easy: http://munin.readthedocs.org/en/latest/tutorial/alert.html

**Comment by edovino** [comment]
This might be a good option to use https://zeropush.com/ - saves everyone from having to run their own push server.

**Comment by quentin-st** [comment]
Thanks for the suggestion!
I already began to implement push notifications, we're using Google Cloud Messaging and the two following projects:
- [Munin for Android GCM Trigger](https://github.com/chteuchteu/Munin-for-Android-GCM-Trigger): users must install it on their servers. munin will call it when alerts are detected
- [Munin for Android GCM Proxy](https://github.com/chteuchteu/Munin-for-Android-GCM-Proxy): this relays alerts to GCM. It is installed on a VPS of mine.

It works really well, I just have to enhance it a bit before merging the notifications branch into master.
