### ISSUE TITLE
V3.6.5-rc3: Server chooser leaves empty tab descriptions

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#27]
Directly after choosing a server it shows the following in the tab descriptions
![screenshot_2015-09-29-10-47-22](https://cloud.githubusercontent.com/assets/5636383/10159324/dfa430fc-6697-11e5-9707-b52c658daebe.png)

Upon the first swipe left or right it displays the descriptions.

**Comment by quentin-st** [comment]
Hi Andre,

Thank you for the bug report!
I tracked this issue (see #25). What we can do for now is:
1. Wait for a fix to be released
2. [Use a previously working PagerTabStrip code](http://stackoverflow.com/questions/32379050/how-can-we-work-around-the-blank-title-in-pagertitlestrip-and-pagertabstrip/32379051#32379051)
3. Use [Android Design Support Library](http://android-developers.blogspot.fr/2015/05/android-design-support-library.html) TabLayout component

I'll try the third one to see if it fits our needs, or fallback to the second one before releasing a new stable version of the app.
