### ISSUE TITLE
Rename Grid Dialog gets unreadable

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#29]
![screenshot_20151027-184009](https://cloud.githubusercontent.com/assets/5636383/10769962/2994188c-7ce9-11e5-962d-17f0ffc51468.png)

**Comment by quentin-st** [comment]
Thanks for the issue report!

There has been some changes to grids that I'd like to revert before releasing to stable channel. As you can see, all grids are grouped in one screen: it is way easier to switch from grid to another.

But:
- grids are slightly slower (all grids have to be loaded to display one)
- more network traffic
- grids list and grid actions are grouped in one screen, which may be confusing
- we have to create a default grid if user hasn't any

So I think that reverting those changes will make your issue go away.
Also, dialogs should adapt their position when the keyboard is opened: it is not on your screenshot, which is weird.

I'll close this issue when the revert will be finished, thank you for noticing this!
