### ISSUE TITLE
Open for discussion: should we include third party plugins documentation?

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#3]
Currently, the app contains documentation for official (core) munin plugins, stored as html files in the app assets. Whenever the currently displayed graph has its documentation available, a "?" menu item is displayed. The HTML file content is then displayed.

I created a list of the (345) most-used plugins from several munin installations in order to see if each plugin is worth being documented.

I also wrote a crawler script in order to extract documentation from the [Munin Plugin Gallery](http://gallery.munin-monitoring.org/index.html), generating either core plugins documentation or both core and third party. At the end of the extraction, usage statistics are generated alongside with HTML files output.
## Results

Here it is:
At the end of **core** plugins extraction, 234 plugins documentation documents has been created. Only 77 out of 345 well-known plugins had a corresponding documentation file.

At the end of **third party** plugins extraction, 280 plugins documentation documents has been created. Only 3 out of 345 well-known plugins had a corresponding documentation file.
### APK weight

Here are some statistics about final production APK size:
- Without any doc: 2,4 MB
- Core doc: 2,6 MB (current scenario)
- Core + third party: 2,9 MB
### Performances

When checking if the currently displayed graph has its documentation file available, an index (JSON array) is parsed and iterated, looking from a reference for the plugin name. Adding 280 items to this index would make the iteration longer.
Beside the fact that plugin documentation availability is now cached (lazy-loading) during session since commit [e059ced](https://github.com/chteuchteu/Munin-for-Android/commit/19adda967e11d616f15d1c1441f452ad65e50960), we shouldn't ignore low performances devices which could be penalized by this change.

So here's the question: should we include third party documentation plugins or not?

**Comment by klaernie** [comment]
Could the documentation be lazy loaded via network? So if a user first tries to access the documentation load it from the server? Also to benefit the intranet users a button to download all doc would be helpful.

After all I think documentation for plugibs is seldomly used, most graphs are well known and munin for android just eases the repeated access to them.

**Comment by quentin-st** [comment]
Downloading all doc from an user action would be a great solution indeed!
I'd like to avoid lazy documentation loading from network, since:
- it will use user's data plan if not using wifi
- 70% of the requests will be useless (no documentation available for the current plugin)
- the loading times wouldn't be quicker

The part I'm worried about is the JSON structure iteration, I'll make some speed tests later (on low performances devices) to see if it's really annoying. Maybe optimizing this JSON structure for easy and quick access?

I also don't know at all if third party plugins are really used...

Thank you for your opinion! :)

**Comment by klaernie** [comment]
Will the doc be downloaded automatically or on user interaction?

After all I don't think there is a big use case for documentation with the client. If we orient on the official web interface for munin we can't find any doc at all. So I would simply offer a link to the documentation "crawler" on munin-for-android.com. I wouldn't worry about repeated internet use, most doc will be read once or twice per user.

**Comment by quentin-st** [comment]
The doc would be downloaded on user interaction, on the device internal memory / SD card.

To introduce documentation reading into the standard use case was a quite interesting idea I think, since users usually don't read documentation in a regular basis. In one hand, it gave docs some visibility, but also helped users to know what really are those unknown plugins that may be installed on their servers. That's why I don't really like the idea of not making it available by default.

I'll make some performances tests in order to see how to enhance documentation availability detection for each plugin.
