### ISSUE TITLE
Dynazoom graphs not showing properly

### ISSUE THREAD

**Issue by Phoenix1o1** [chteuchteu/Munin-for-Android#32]
Hi. i've been using Munin-for-Android for a while now, but i am having issues using the zoom function. when i try it it only shows a broken "danger" icon. I can see the zoomlines, and they seem to be working, but i had no luck in showing any graph. Zoom works fine otherwise via webbrowser and even from mobile browser. i waited to report this problem since the previus app update and i really dont know what to make of it. Any help apreciated

**Comment by Phoenix1o1** [comment]
![screenshot_2016-01-01-16-55-20](https://cloud.githubusercontent.com/assets/5053221/12071359/9c44ae9e-b0a8-11e5-95ca-60dc90e9af26.jpg)

**Comment by quentin-st** [comment]
Hi @Phoenix1o1! Thank you for reporting this issue.

First, could you try to rescan the server (hit the 3-dots icon and select "Rescan" on the Servers screen)? If this does not work, could you try to remove this server and re-add it again?

If this does not work, please switch to the beta channel ([instructions are here](https://github.com/chteuchteu/Munin-for-Android#beta)) and check again

Please let me know if any of these instructions fixes your issue!

**Comment by quentin-st** [comment]
I just saw your issue on munin-monitoring project ([munin-monitoring/munin#460](https://github.com/munin-monitoring/munin/issues/460#issuecomment-168269650)).

Munin for Android actually uses munin's web pages URLs to generate dynazoom graphs URLs. This issue (chteuchteu/Munin-for-Android#32) is caused by munin's one: as long as URLs will be broken on your installation, the app won't be able to handle those correctly.

**Comment by Phoenix1o1** [comment]
Ok, i worked around that issue (munin-monitoring/munin#460) before even posting here, but i still get the same problem. i re-added the server, reinstalled the app, and got to the drastic point of reinstalling munin just to get it working with the app, and i still haven't solved it. as i said, all dynazoom are working otherwise, even tried them from Chrome browser on my cellphone, and on the stock android broswer. even other computers pick it up right, but i'm having an idea. Might it be that it cannot load that graph because it isn,t full? i mean, when i tried munin was a fresh install, and the graph was only half-populated, maybe it must be all filled up to see something. anyway, ill switch to beta asap, maybe even tomorrow if i can spare some time, and let you know. thanks for the quick answer. Andrea

**Comment by quentin-st** [comment]
Hi Andrea! First, please know that you should not have to reinstall munin to make Munin for Android work! Munin for Android should adapt to munin, not otherwise.
Plus, graphs do not have to be fully populated to be shown in Munin for Android, so that's not the issue either.
Could you try the beta channel as explained above please? This may fix the issue. 

Please let me know if that works!

**Comment by Phoenix1o1** [comment]
Hi, writing to keep you informed. Despite having tried everything i could think off, and after a week of trying I’m still stuck. those graphs wont show up regardless of what i do. Even with the beta app, 3.6.5-beta7 as of now, i see nothing.
But i have an update. Sometimes if i zoom in on the apparently broken image, i can catch a glimpse of the graph, and it appears to be zoomed. Then the broken image pops up again. I am starting to think maybe the problem lies in my cellphone and not on the app itself.
Might that be of any use, it is a ZenFone 2, Z00AD running stock 5.0
Thanks for all the help and for the great app btw.

**Comment by quentin-st** [comment]
Hi,
In #33, you seem to have managed to make it work. What was the fix? Where did it come from?
I should dig into the code to be sure, but this issue seems weird indeed...

**Comment by Phoenix1o1** [comment]
At this point i'm not sure at all about where the fix came from. I made some changes on my munin config and my apache config,and i think at some point i switched apache module mpm_prefork with mpm_event as suggested somewhere in the internet, but im not even sure it has done anything. The day i got tired of trying i opened the app and it was just working. I should have taken more care trying to do things in order and checking if it changed something. Anyway, if you want, i can try and send you all my configs and eventually some logs.
Next week I am going to put a brand new server at work, and i already have a full day booked as Munin-Android install. i'll see if i get any issue on a different machine, with a different base setup, and i will let you know how will that go. thanks a lot for your time and for the awesome app again.

**Comment by klaernie** [comment]
@Phoenix1o1 just as a precaution grab [etckeeper](http://etckeeper.branchable.com/) before you start, that way you have a git repo for everything in /etc and have a deep log on what happened. You just need to commit every single change you do manually.and ifbyou again get into a state like now, where it wasn't working and now is you can git bisect it.

**Comment by quentin-st** [comment]
@Phoenix1o1 : thank you for those precision! Please note that Munin for Android deduces your server configuration by browsing its report pages. So if it works on your browser, it _should_ work on Munin for Android.

@klaernie Nice, I wasn't aware of etckeep, seems nice!

I believe this issue can be closed, don't hesitate to comment here if it should be reopened.
Thank you for the followup!
