### ISSUE TITLE
Translatable files do not reflect current state.

### ISSUE THREAD

**Issue by comradekingu** [chteuchteu/Munin-for-Android#38]
https://hosted.weblate.org/translate/munin-for-android/ has strings in it that are fixed in
strings.xml on master

https://hosted.weblate.org/translate/munin-for-android/strings/nb_NO/?checksum=585f4fe6d53198f0

says "taping", whereas it is fixed here:

https://github.com/chteuchteu/Munin-for-Android/blob/52292cb95fc93ff6d70f3776bb014e2dd1db4e4c/muninforAndroid/src/main/res/values/strings.xml#L124

So either "release" or the "l10n" is what is on Weblate

**Comment by quentin-st** [comment]
Thank you for this! I just synced both branches (i18n had a commit that wasn't in master, and was several commit late from it)
