### ISSUE TITLE
Upload to F-Droid and/or releases on Github

### ISSUE THREAD

**Issue by Thor77** [chteuchteu/Munin-for-Android#4]
Hey,
since this app is Open Source now,
it would be very nice, if users who doesn't want google services, can use this app.
=> Please upload this app to F-Droid and/or provide precompiled .apk-files

**Comment by quentin-st** [comment]
Hi!

The app is still a "freemium" app so it still needs Google Play to unlock premium features (by buying the Premium Pack unlocking app).

But I just started providing compiled apk files in the [releases page of the repository](https://github.com/chteuchteu/Munin-for-Android/releases) so you can install the app if you don't use Google Play. Please note that you'll have to handle updates by yourself.

**Comment by Thor77** [comment]
Uhm, thats really uncommon for an open source app,
i thought the source provided here will provide _all_ features.
Maybe you can think about this, i think it won't cost you too much income if you provide the premium-version here and on F-Droid.
And i think the App will not run on devices without Google Services, if it needs them to unlock premium (cant test it).

**Comment by quentin-st** [comment]
The source provided here are covering all the features available in the premium version of Munin for Android. Instead, the unlocking app isn't provided.

Also, the free version of the app should work without any problem on devices without Google Services (this has been tested)!

It's not a problem of lowering my incomes, but instead allowing some users to have the whole features without paying but asking others to pay for those.
