### ISSUE TITLE
Latest Munstrap template compatibility broken

### ISSUE THREAD

**Issue by misotolar** [chteuchteu/Munin-for-Android#40]
The app don't show any graphs using latest Munstrap template source from [munin-monitoring/contrib](https://github.com/munin-monitoring/contrib) repo.

Default Munin template and Munstrap template from [jonnymccullagh/munstrap](https://github.com/jonnymccullagh/munstrap) legacy repo works ok.

**Comment by quentin-st** [comment]
Indeed, Munstrap isn't officially supported - I recommend to disable it, scan your installation for nodes & plugins, and re-enable it afterwards

**Comment by misotolar** [comment]
Sorry about that, I got confused about Munstrap template support. Scan installation for nodes with legacy Munstrap template before enable new source also solves the problem.

**Comment by quentin-st** [comment]
Not a problem! Glad to know it worked for you.

**Comment by VladiCz** [comment]
I was having this problem for **weeks** and I was unable to figure it out, especially when https://www.munin-for-android.com/ sais on homepage, that Munstrap is supported. **Gladly i found this thread.**   I didn't know, there is an older version of Munstrap.
I'm voting for Munstrap support in latest version!

**Comment by quentin-st** [comment]
@VladanZ : thanks for the notice, I'll update the website!

Supporting Munstrap's latest version wouldn't be *that* hard, but since we should support all of its versions, unit tests are mandatory. (adding some to ensure that all versions of munin are supported wouldn't hurt)

**Comment by WiredWonder** [comment]
Any updates on this? I find it odd that at least using the mainline version of munstrap can't be supported.
