### ISSUE TITLE
Trigger alert is not received by android device anymore

### ISSUE THREAD

**Issue by Catscrash** [chteuchteu/Munin-for-Android#44]
Hi,

since a while the trigger push notifications don't reach the device anymore. I re-added the device, but even the test notification is not received. Is this working for all of you? Is there anything that has changed?

thanks

**Comment by quentin-st** [comment]
I identified the issue and am actively working on it. I'll post updates on this thread: https://twitter.com/MuninforAndroid/status/1099616797865766913
I'm deeply sorry about the inconvenience.

Thank you for using Munin for Android!

**Comment by quentin-st** [comment]
Issue 1 has been fixed and deployed, as stated in the Twitter thread.
Another issue (Google Cloud Messaging being sunseted) arose, I fixed it and am currently preparing another release for it.
