### ISSUE TITLE
Find a way to display SVG graphs

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#5]
There are good news: munin will soon (currently in dev) generate SVG graphs that Munin for Android will be able to download and render!

This is an SVG graph:

![Isn't that great?](http://demo.munin-monitoring.org/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/multicpu1sec-week.svg)

The great new here is that we won't have to mess around with dynazoom to get decent quality graphs, but download and display the SVG version instead.

Bad news are that I haven't found any decent Android library to render those. Indeed, every library I tried just fails rendering the graph since it is more complex than average SVG files.
## SVG thoughts

But should we integrate SVG graphs into the app?

Pros:
- **Better quality**, without even having to think about screen resolution

Cons:
- **Heavier than standard graph** (SVG files weights ~170 kB, standard graphs files weights ~100 kB)
- **Slower to render**: a basic bitmap will be rendered quicker than an SVG graph
- We have to find a **compatible SVG library**
## Conclusion?

Currently, the SVG downloading process has already been integrated (downloading the SVG file instead of the Bitmap version, storing SVG availability (boolean) in local DB), but displaying it in the ImageView isn't ready yet. This code will stay while looking for a proper SVG library but should be removed soon if nothing's found.

**Comment by quentin-st** [comment]
Finally, the SVG graphs feature will be put aside for now, and related code will be deleted

**Comment by klaernie** [comment]
As a followup question: would it be possible to grab the raw datapoints from the Munin server and graph them directly in the app? I think there should be nice graphing libraries around, I especially like the functionality that the graphs in Google Fit provide. @chteuchteu any ideas on that?

**Comment by quentin-st** [comment]
In a recent development update, munin team added alternatives data sources: instead of just having a png file (apache_accesses-day.png for example), we also have
- SVG ([apache_accesses-day.svg](http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.svg))
- Json ([apache_accesses-day.svg](http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.json))
- Xml ([apache_accesses-day.svg](http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.xml))

So yes, raw data is available! Since this is a development version, we will have to wait a little bit longer to see users installations implementing those features. But we can already implement it, test it (using demo.munin-monitoring.org) and make it available

If we implement this, here are the pros and cons:

### Pros
- Downloaded file (PNG vs Json) weight is lower (~40ko for PNG vs ~20ko for Json)
- We have full control over graph (user will be able to hide some plots for example)

### Cons
- We have to find a compatible library. There are a lot out there, so we have to chose the good one
- Graph rendering will be slower than just displaying the PNG version (we have to parse the Json/Xml file, instantiate the graph, and display it). I already worked with such libraries before (in [Freebox Stats](https://github.com/chteuchteu/Freebox-Stats)), and performances can be very bad on plots with a lot of points

I also like Google Fit graphs (very Material), but I don't think that they would be suitable with munin since Google Fit graphs only display a reduced amount of points
