### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by brknkfr** [chteuchteu/Munin-for-Android#50]
Push notifications stopped working a while ago, more precisely a week ago.

When trying to send push messages via Munin-for-Android-GCM-Trigger, no push notification is received. It seems, that gcm-proxy.munin-for-android.com is down due to the recent events in OVH data centers.

Will there be a replacement anytime soon?

**Comment by quentin-st** [comment]
You're totally right - the server that hosted the main GCM proxy project was affected in the recent incident.
I'll try to restore it asap

In the meantime, you could try to host your own proxy instance

**Comment by brknkfr** [comment]
> In the meantime, you could try to host your own proxy instance
>
I tried, unfortunately without success until now.

I got a domain up and running with the symfony backend, changed the trigger url in Munin-for-Android-GCM-Trigger, triggers are fired correctly and received by the smyfony backend, but somehow not relayed to the firebase cloud messaging or so.

I registered a firebase "web" project on google but I don't know what key exactly to use as "firebase_api_key" in Munin-for-Android-GCM-Proxy. Is the the projects key or the cloud messaging server key?

Or could you provide a mini howto for the installation of Munin-for-Android-GCM-Proxy? Or do I have to compile my own Munin-for-Android to use a "custom" proxy?

**Comment by quentin-st** [comment]
You have to specify the cloud messaging server key, indeed!
You shouldn't have to build the app to use a custom proxy (that was the point of letting users specify their own proxy instance)

I've rewritten this project to upgrade Symfony (and be compatible with PHP7.4), and reinstalled it on a shiny new server: the GCM proxy is back online: https://gcm-proxy.munin-for-android.com/ping

I was able to trigger a test notification on my device using the GCM-Trigger with its default configuration: could you try on your side to see if everything works please?

![Screenshot_20210324-182846~2](https://user-images.githubusercontent.com/1551971/112357099-81478900-8ccf-11eb-81db-d98cfc11cec6.png)


It seems that users are receiving notifications: the stat table (only updated if users opt-in to stats) tells us that the endpoint received a hit at `2021-03-24 17:30:35`.

Please let me know if it works for you!

**Comment by brknkfr** [comment]
Notifications over the main GCM proxy works again, thanks.

For the installation of an own GCM proxy I'm going to open another issue (https://github.com/chteuchteu/Munin-for-Android-GCM-Proxy/issues/2)
