### ISSUE TITLE
No notifications at all since several weeks

### ISSUE THREAD

**Issue by Yogi4301** [chteuchteu/Munin-for-Android#52]
Hi,
since several weeks I get no notifications at all. If I use main.py for a test message I get no alarm but also no error occurs.
I'm using munin for android on a raspberrypi with bullseye

**Comment by quentin-st** [comment]
Hello @Yogi4301 ! An old issue was opened on https://github.com/quentin-st/Munin-for-Android-GCM-Proxy/issues/2: I'm currently looking into it, I'll keep you in touch!

**Comment by quentin-st** [comment]
@Yogi4301 The issue is now fixed! I was able to trigger a notification on my device through https://gcm-proxy.munin-for-android.com/trigger/declareAlert. Please let me know if everything works fine on your side.

**Comment by Yogi4301** [comment]
@quentin-st Thanks a lot - everything is working again.
