### ISSUE TITLE
What should be displayed on home screen?

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#6]
Currently, the Munin for Android homescreen seems quite useless since it doesn't show any relevant information. Instead, on app launch, the drawer is open waiting for user decision.

Instead of losing this space, we could display some useful information. What information should be displayed?

Some early ideas would be to display one (or some) of these:
- Servers list
- Labels list
- Grids list
- Most seen graphs (we should then have a counter for each plugin which isn't nice)

Any ideas?

Currently useless app home screen:
![screenshot_2015-01-28-16-11-46](https://cloud.githubusercontent.com/assets/1551971/5940187/7680bab2-a709-11e4-875b-8cec891cd61a.png)

**Comment by klaernie** [comment]
I think actual information would be most valuable. So leave the penultimate choice to the user, and allow them to display a grid, or one specific server, or all current alerts, with the default of displaying the last shown activity.

**Comment by quentin-st** [comment]
> I think actual information would be most valuable.

Yes indeed!

When I asked myself this question, I was more thinking about contextual information instead of an entiere app screen. First, this is easier since the application uses Activities and not Fragments (yet?). Then, I imagined the main activity (first screen) to be a shortcut to different parts of the app (showing the servers list, and allowing the user to switch to one) instead of displaying a whole Activity on it.

But that actually makes sense since I think there are graphs users (users who mostly use the app only through graphs) and grids users (same but with grids).

That would mean migrating somes activities (grids for example) from simple Activity to FragmentActivity

**Comment by quentin-st** [comment]
I pushed some work this afternoon: now, the user can choose the default activity on launch (currently, only grids are supported).

In order to avoid reloading all graphs each time we reach Activity_Main, the user has to click on a button in order to trigger graphs loading.

Here's a functional example:

![2015-02-04 17 52 38](https://cloud.githubusercontent.com/assets/1551971/6046346/87538e4e-aca1-11e4-955e-8cd4cc3696e2.png)

**Comment by quentin-st** [comment]
Version 3.5 will bring the ability to show either one grid or one label on homescreen, this can be closed!
