### ISSUE TITLE
servers are duplicating

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#8]
In the screenshot you can see, that the hosts in the first two groups are identical, but they are not supposed to be. The second group should contain three other servers, and none of the in the above group.

![screenshot_2015-03-19-15-30-02](https://cloud.githubusercontent.com/assets/5636383/6732564/f9a67d0e-ce4c-11e4-8978-ff0a8c2f5842.png)

**Comment by quentin-st** [comment]
Have you tried to rescan each master?
Is hsh-online.com linked with ak-online.be?

**Comment by klaernie** [comment]
Okay, finally I understand the issue: the semantics of the grouping has changed. Previously it reflected the groups defined in the munin configuration, now it only reflects the the master server, with the groups feature unavailable. So when I refreshed the master server hsh-online.com it loaded everything it could find under this master server, omitting the server that was missing.
