### ISSUE TITLE
server chooser list is not adapted to the content or screen size

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#9]
The list on top should be sized automatically to accommodate its contents, or at maximum fill the screen. Currently it seems like the list is set to a fix width in pixels, as it was way bigger on my older device which had a lower screen resolution. 
![screenshot_2015-03-18-09-01-01](https://cloud.githubusercontent.com/assets/5636383/6732696/cb77db16-ce4d-11e4-9dab-e5b480ccd5d0.png)

**Comment by quentin-st** [comment]
The AlertDialog list was indeed fixed in the code. It looked perfect on my One Plus One, but seems weird on yours, indeed!
Just switched it to WRAP_CONTENT.
